version: 2.1


jobs:
  build:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.8"
    steps:
      - checkout
      - run: python -m pip install --upgrade pip


workflows:
  jobs:
    - build